- name: 检查 mysql 是否已安装
  stat: path="{{ v_mysql_data_dir }}"
  register: install_check
  ignore_errors: true

- name: 如目录存在则中断退出安装  
  fail: msg="安装失败：mysql数据目录 {{ v_mysql_data_dir }} 已存在，请检查！"
  when: install_check.stat.exists==true

- name: 准备 mysql 工作目录
  file: name={{ item }} state=directory owner=mysql group=mysql
  with_items:
  - "{{ v_mysql_work_dir }}"
  - "{{ v_mysql_data_dir }}"
  - "{{ v_mysql_binlog_dir }}"
  - "{{ v_mysql_slowlog_dir }}"
  - "{{ v_mysql_backup_dir }}"
  - "{{ v_mysql_command_dir }}"
  - "{{ v_mysql_undolog_dir }}"
  - "{{ v_mysql_tmp_dir }}"

- name: 初始化配置文件
  template: src=my.ini dest=/etc/my.cnf

- name: 初始化数据库(非安全模式)
  shell: /usr/sbin/mysqld --defaults-file=/etc/my.cnf --user=mysql --initialize-insecure
  when: v_mysql_initialize_secure=="0"
  
- name: 初始化数据库(安全模式，安装完后需手工设置密码，初始密码位于{{ v_mysql_data_dir }}/{{ v_mysql_port }}_error.log)
  shell: /usr/sbin/mysqld --defaults-file=/etc/my.cnf --user=mysql --initialize
  when: v_mysql_initialize_secure=="1"

- name: 启动 mysql 服务，并设置开机自启动
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: 设置数据库密码
  shell: mysql -e "set password = password('{{ v_mysql_password }}');"
  when: v_mysql_initialize_secure=="0"

- name: 添加 root 远程登录帐号
  shell: mysql -p'{{ v_mysql_password }}' -e "grant all privileges on *.* to 'root'@'%' identified by '{{ v_mysql_password }}' with grant option;"
  when: v_mysql_initialize_secure=="0"

- name: 刷新权限使生效
  shell: mysql -p'{{ v_mysql_password }}' -e "flush privileges;"
  when: v_mysql_initialize_secure=="0"

