- name: 工作目录
  file: name={{ item }} state=directory
  with_items:
  - "{{ work_dir }}"
  - "{{ backup_dir }}"

- name: 拷贝脚本文件
  copy: src={{ item }} dest={{ work_dir }}/{{ item }} mode=0755
  with_items:
  - run_backup.sh
  - mysql_backup.sh
  - mysql_backup_extra.sh
  - mysql_merge.sh
  - mysql_restore.sh

- name: 准备备份配置文件
  template: src=mysql_backup.ini dest={{ work_dir }}/mysql_backup.ini
  
# 查看定时任务命令：crontab -l 
# 文件存放目录：cat /var/spool/cron/root
- name: 设置数据库增量同步定时任务
  cron:
    name: "mysql数据库({{ port }})增量同步"
    minute: "{{ cron_minute }}"
    hour: "{{ cron_hour }}"
    user: root 
    job: "cd {{ work_dir }} && ./run_backup.sh -F 0"

# - name: 安装必备组件
#   yum: update_cache=yes name={{ item }} state=present
#   with_items:
#   - perl-CPAN
#   - perl-DBD-MySQL
#   - perl
#   - make 
#   - gcc 
#   - gcc-c++ 
#   - patch 
#   - libgcrypt
#   - libgcrypt-devel 
#   - libaio 
#   - libaio-devel 
#   - automake 
#   - autoconf
#   - bzr 
#   - bison 
#   - libtool 
#   - perl-Time-HiRes 
#   - rsync
#   - sendmail
#   - mailx
# 
# - name: 下载 XtraBackup 安装包
#   get_url: url={{ item }} dest=/tmp
#   with_items:
#   - "{{ xtrabackup_url }}"
# 
# - name: 解压 XtraBackup 安装包
#   unarchive:
#     # src也可以直接填写一个URL地址直接进行下载解压
#     src: "/tmp/Percona-XtraBackup-2.2.10-re623acb-el7-x86_64-bundle.tar"
#     copy: no
#     dest: "/tmp"
# 
# - name: 安装 XtraBackup
#   shell: "rpm -ivh /tmp/percona-xtrabackup-2.2.10-1.el7.x86_64.rpm"
#   ignore_errors: true
# 
# - name: 准备mailx配置文件
#   template: src=mail.rc dest=/etc/mail.rc
# 
# - name: 重启 sendmail 服务，并开启自启动
#   systemd:
#     name: sendmail
#     daemon_reload: yes
#     state: restarted
#     enabled: yes