- name: 安装 xtrabackup yum 仓库
  shell: "yum -y install {{ v_xtrabackup_repo_url }}"
  ignore_errors: true
  
- name: 安装 percona-xtrabackup
  shell: "yum -y install percona-xtrabackup-24"

- name: 安装必备组件
  yum: update_cache=yes name={{ item }} state=present
  with_items:
  - sendmail
  - mailx

- name: 工作目录
  file: name={{ item }} state=directory
  with_items:
  - "{{ v_mysql_work_dir }}"
  - "{{ v_mysql_command_dir }}"
  - "{{ v_mysql_backup_dir }}"

- name: 拷贝脚本文件
  copy: src={{ item }} dest={{ v_mysql_command_dir }}/{{ item }} mode=0755
  with_items:
  - run_backup.sh
  - mysql_backup.sh
  - mysql_backup_extra.sh
  - mysql_merge.sh
  - mysql_restore.sh

- name: 初始化备份配置文件
  template: src=mysql_backup.ini dest={{ v_mysql_command_dir }}/mysql_backup.ini

# 查看定时任务命令：crontab -l 
# 文件存放目录：cat /var/spool/cron/root
- name: 设置数据库增量同步定时任务
  cron:
    name: "mysql数据库({{ v_mysql_port }})增量同步"
    minute: "{{ v_cron_minute }}"
    hour: "{{ v_cron_hour }}"
    user: root 
    job: "cd {{ v_mysql_command_dir }} && ./run_backup.sh -F 0"

- name: 准备 mailx 配置文件
  template: src=mail.rc dest=/etc/mail.rc

- name: 重启 sendmail 服务，并开启自启动
  systemd:
    name: sendmail
    daemon_reload: yes
    state: restarted
    enabled: yes